services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
    - network1 
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: converter
      POSTGRES_PASSWORD: converter1234
      POSTGRES_DB: converter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - network1
volumes:
  redis-data:
  postgres_data: