name: Microservices-Converter-Demo
include:
  - docker-compose-monitoring.yaml
  - docker-compose-logging.yaml 
  - docker-compose-tracing.yaml 
  - docker-compose-databases.yaml
services:
  
  frontend:
      build:
        context: src/frontend
      container_name: frontend 
      ports:
      - 8080:8080
      networks:
      - network1
      environment:
      - DOCKER_ENVIRONMENT=true
      - LOG_DIR=/root/logs
      - GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID_CREDS
      - GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET_CREDS
      - REDIRECT_CALLBACK_URL=http://localhost:8080/google/auth/callback
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SECRET=idwoeoejinkwnks
      - TEXT_TO_SPEECH_HOST=text-to-speech
      - TEXT_TO_SPEECH_PORT=8081
      - VIDEO_TO_AUDIO_HOST=video-to-audio
      - VIDEO_TO_AUDIO_PORT=8082
      - IMAGE_TO_PDF_HOST=image-to-pdf
      - IMAGE_TO_PDF_PORT=8083
      - OTLP_COLLECTOR_HOST=otel-collector
      - OTLP_COLLECTOR_PORT=4318
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - POSTGRES_USER=converter
      - POSTGRES_PASSWORD=converter1234
      - POSTGRES_DB=converter
      - POSTGRES_HOST=postgres 
      - POSTGRES_PORT=5432
     
      volumes:
      - ./logs:/root/logs
      depends_on:
       redis:
          condition: service_started
       postgres:
          condition: service_healthy
       
  text-to-speech:
      build:
        context: src/text-to-speech 
      container_name: text-to-speech 
      ports:
      - 8081:8081 
      - 9091:9090
      networks:
      - network1
      environment:
      - FILE_UPLOADER_HOST=file-uploader
      - FILE_UPLOADER_PORT=8084
      - OTLP_COLLECTOR_HOST=otel-collector
      - OTLP_COLLECTOR_PORT=4318
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
  video-to-audio:
      build:
        context: src/video-to-audio 
      container_name: video-to-audio 
      ports:
      - 8082:8082
      - 9092:9090
      networks:
      - network1
      environment:
      - DOCKER_ENVIRONMENT=true
      - LOG_DIR=/root/logs
      - FILE_UPLOADER_HOST=file-uploader
      - FILE_UPLOADER_PORT=8084
      - OTLP_COLLECTOR_HOST=otel-collector
      - OTLP_COLLECTOR_PORT=4318
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8082
      volumes:
      - ./logs:/root/logs

  image-to-pdf:
      build:
        context: src/image-to-pdf
      container_name: image-to-pdf 
      ports:
      - 8083:8083 
      - 9093:9090
      networks:
      - network1
      environment:
      - FILE_UPLOADER_HOST=file-uploader
      - FILE_UPLOADER_PORT=8084
      - OTLP_COLLECTOR_HOST=otel-collector 
      - OTLP_COLLECTOR_PORT=4318
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8083
  file-uploader:
      build:
        context: src/file-uploader
        
      container_name: file-uploader
      ports:
      - 8084:8084
      - 9094:9090
      networks:
      - network1
      environment:
      - DOCKER_ENVIRONMENT=true
      - LOG_DIR=/root/logs
      - GOOGLE_APPLICATION_CREDENTIALS=/root/key.json
      - GCP_SERVICE_ACCOUNT=GCP_SERVICE_ACCOUNT_NAME
      - OTLP_COLLECTOR_HOST=otel-collector
      - OTLP_COLLECTOR_PORT=4318
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8084
      - GCS_BUCKET_NAME=GCS_BUCKET
      volumes:
      - ./key.json:/root/key.json:ro
      - ./logs:/root/logs
  
  
  



networks:
    network1:
      driver: bridge


