services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317" # OTLP gRPC endpoint
      - "4318:4318" # OTLP HTTP endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command:
      --config=/etc/otel-collector-config.yaml
    networks:
    - network1
    

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
     # Jaeger Agent
    networks:
    - network1
  