// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: file-uploader.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileUploaderService_Upload_FullMethodName = "/proto.FileUploaderService/Upload"
)

// FileUploaderServiceClient is the client API for FileUploaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileUploaderServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error)
}

type fileUploaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileUploaderServiceClient(cc grpc.ClientConnInterface) FileUploaderServiceClient {
	return &fileUploaderServiceClient{cc}
}

func (c *fileUploaderServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileChunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileUploaderService_ServiceDesc.Streams[0], FileUploaderService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileChunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileUploaderService_UploadClient = grpc.ClientStreamingClient[FileChunk, UploadResponse]

// FileUploaderServiceServer is the server API for FileUploaderService service.
// All implementations must embed UnimplementedFileUploaderServiceServer
// for forward compatibility.
type FileUploaderServiceServer interface {
	Upload(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error
	mustEmbedUnimplementedFileUploaderServiceServer()
}

// UnimplementedFileUploaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileUploaderServiceServer struct{}

func (UnimplementedFileUploaderServiceServer) Upload(grpc.ClientStreamingServer[FileChunk, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFileUploaderServiceServer) mustEmbedUnimplementedFileUploaderServiceServer() {}
func (UnimplementedFileUploaderServiceServer) testEmbeddedByValue()                             {}

// UnsafeFileUploaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileUploaderServiceServer will
// result in compilation errors.
type UnsafeFileUploaderServiceServer interface {
	mustEmbedUnimplementedFileUploaderServiceServer()
}

func RegisterFileUploaderServiceServer(s grpc.ServiceRegistrar, srv FileUploaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileUploaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileUploaderService_ServiceDesc, srv)
}

func _FileUploaderService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileUploaderServiceServer).Upload(&grpc.GenericServerStream[FileChunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileUploaderService_UploadServer = grpc.ClientStreamingServer[FileChunk, UploadResponse]

// FileUploaderService_ServiceDesc is the grpc.ServiceDesc for FileUploaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileUploaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileUploaderService",
	HandlerType: (*FileUploaderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FileUploaderService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "file-uploader.proto",
}
