// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: video-to-audio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertVideoToAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertVideoToAudioRequest) Reset() {
	*x = ConvertVideoToAudioRequest{}
	mi := &file_video_to_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertVideoToAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertVideoToAudioRequest) ProtoMessage() {}

func (x *ConvertVideoToAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_to_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertVideoToAudioRequest.ProtoReflect.Descriptor instead.
func (*ConvertVideoToAudioRequest) Descriptor() ([]byte, []int) {
	return file_video_to_audio_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertVideoToAudioRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ConvertVideoToAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertVideoToAudioResponse) Reset() {
	*x = ConvertVideoToAudioResponse{}
	mi := &file_video_to_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertVideoToAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertVideoToAudioResponse) ProtoMessage() {}

func (x *ConvertVideoToAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_to_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertVideoToAudioResponse.ProtoReflect.Descriptor instead.
func (*ConvertVideoToAudioResponse) Descriptor() ([]byte, []int) {
	return file_video_to_audio_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertVideoToAudioResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_video_to_audio_proto protoreflect.FileDescriptor

var file_video_to_audio_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x74, 0x6f, 0x2d, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a,
	0x1a, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x6f, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x22, 0x2f, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x54, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x32, 0x74, 0x0a, 0x1c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x6f, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x54, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x54, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_video_to_audio_proto_rawDescOnce sync.Once
	file_video_to_audio_proto_rawDescData = file_video_to_audio_proto_rawDesc
)

func file_video_to_audio_proto_rawDescGZIP() []byte {
	file_video_to_audio_proto_rawDescOnce.Do(func() {
		file_video_to_audio_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_to_audio_proto_rawDescData)
	})
	return file_video_to_audio_proto_rawDescData
}

var file_video_to_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_video_to_audio_proto_goTypes = []any{
	(*ConvertVideoToAudioRequest)(nil),  // 0: proto.ConvertVideoToAudioRequest
	(*ConvertVideoToAudioResponse)(nil), // 1: proto.ConvertVideoToAudioResponse
}
var file_video_to_audio_proto_depIdxs = []int32{
	0, // 0: proto.VideoToAudioConverterService.Convert:input_type -> proto.ConvertVideoToAudioRequest
	1, // 1: proto.VideoToAudioConverterService.Convert:output_type -> proto.ConvertVideoToAudioResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_to_audio_proto_init() }
func file_video_to_audio_proto_init() {
	if File_video_to_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_to_audio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_to_audio_proto_goTypes,
		DependencyIndexes: file_video_to_audio_proto_depIdxs,
		MessageInfos:      file_video_to_audio_proto_msgTypes,
	}.Build()
	File_video_to_audio_proto = out.File
	file_video_to_audio_proto_rawDesc = nil
	file_video_to_audio_proto_goTypes = nil
	file_video_to_audio_proto_depIdxs = nil
}
