// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: text-to-speech.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextToSpeechConverterService_Convert_FullMethodName = "/proto.TextToSpeechConverterService/Convert"
)

// TextToSpeechConverterServiceClient is the client API for TextToSpeechConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextToSpeechConverterServiceClient interface {
	Convert(ctx context.Context, in *ConvertTextToSpeechRequest, opts ...grpc.CallOption) (*ConvertTextToSpeechResponse, error)
}

type textToSpeechConverterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextToSpeechConverterServiceClient(cc grpc.ClientConnInterface) TextToSpeechConverterServiceClient {
	return &textToSpeechConverterServiceClient{cc}
}

func (c *textToSpeechConverterServiceClient) Convert(ctx context.Context, in *ConvertTextToSpeechRequest, opts ...grpc.CallOption) (*ConvertTextToSpeechResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertTextToSpeechResponse)
	err := c.cc.Invoke(ctx, TextToSpeechConverterService_Convert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextToSpeechConverterServiceServer is the server API for TextToSpeechConverterService service.
// All implementations must embed UnimplementedTextToSpeechConverterServiceServer
// for forward compatibility.
type TextToSpeechConverterServiceServer interface {
	Convert(context.Context, *ConvertTextToSpeechRequest) (*ConvertTextToSpeechResponse, error)
	mustEmbedUnimplementedTextToSpeechConverterServiceServer()
}

// UnimplementedTextToSpeechConverterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextToSpeechConverterServiceServer struct{}

func (UnimplementedTextToSpeechConverterServiceServer) Convert(context.Context, *ConvertTextToSpeechRequest) (*ConvertTextToSpeechResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedTextToSpeechConverterServiceServer) mustEmbedUnimplementedTextToSpeechConverterServiceServer() {
}
func (UnimplementedTextToSpeechConverterServiceServer) testEmbeddedByValue() {}

// UnsafeTextToSpeechConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextToSpeechConverterServiceServer will
// result in compilation errors.
type UnsafeTextToSpeechConverterServiceServer interface {
	mustEmbedUnimplementedTextToSpeechConverterServiceServer()
}

func RegisterTextToSpeechConverterServiceServer(s grpc.ServiceRegistrar, srv TextToSpeechConverterServiceServer) {
	// If the following call pancis, it indicates UnimplementedTextToSpeechConverterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextToSpeechConverterService_ServiceDesc, srv)
}

func _TextToSpeechConverterService_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertTextToSpeechRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextToSpeechConverterServiceServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextToSpeechConverterService_Convert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextToSpeechConverterServiceServer).Convert(ctx, req.(*ConvertTextToSpeechRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextToSpeechConverterService_ServiceDesc is the grpc.ServiceDesc for TextToSpeechConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextToSpeechConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TextToSpeechConverterService",
	HandlerType: (*TextToSpeechConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _TextToSpeechConverterService_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "text-to-speech.proto",
}
