apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
      app: {{ .Values.name }}
#  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- if .Values.httpPort }}  
    - protocol: TCP
      name: http-web
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
    {{- end }}
    {{- if .Values.grpcPort }}  
    - protocol: TCP
      name: grpc-web
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
    {{- end }}
    
