// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.12.4
// source: text-to-speech.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertTextToSpeechRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertTextToSpeechRequest) Reset() {
	*x = ConvertTextToSpeechRequest{}
	mi := &file_text_to_speech_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertTextToSpeechRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertTextToSpeechRequest) ProtoMessage() {}

func (x *ConvertTextToSpeechRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_to_speech_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertTextToSpeechRequest.ProtoReflect.Descriptor instead.
func (*ConvertTextToSpeechRequest) Descriptor() ([]byte, []int) {
	return file_text_to_speech_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertTextToSpeechRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ConvertTextToSpeechResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertTextToSpeechResponse) Reset() {
	*x = ConvertTextToSpeechResponse{}
	mi := &file_text_to_speech_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertTextToSpeechResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertTextToSpeechResponse) ProtoMessage() {}

func (x *ConvertTextToSpeechResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_to_speech_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertTextToSpeechResponse.ProtoReflect.Descriptor instead.
func (*ConvertTextToSpeechResponse) Descriptor() ([]byte, []int) {
	return file_text_to_speech_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertTextToSpeechResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_text_to_speech_proto protoreflect.FileDescriptor

var file_text_to_speech_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x65, 0x78, 0x74, 0x2d, 0x74, 0x6f, 0x2d, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x1a, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70,
	0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x2f, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f,
	0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0x72, 0x0a, 0x1c, 0x54, 0x65, 0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x52, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54,
	0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x54, 0x6f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_text_to_speech_proto_rawDescOnce sync.Once
	file_text_to_speech_proto_rawDescData = file_text_to_speech_proto_rawDesc
)

func file_text_to_speech_proto_rawDescGZIP() []byte {
	file_text_to_speech_proto_rawDescOnce.Do(func() {
		file_text_to_speech_proto_rawDescData = protoimpl.X.CompressGZIP(file_text_to_speech_proto_rawDescData)
	})
	return file_text_to_speech_proto_rawDescData
}

var file_text_to_speech_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_text_to_speech_proto_goTypes = []any{
	(*ConvertTextToSpeechRequest)(nil),  // 0: proto.ConvertTextToSpeechRequest
	(*ConvertTextToSpeechResponse)(nil), // 1: proto.ConvertTextToSpeechResponse
}
var file_text_to_speech_proto_depIdxs = []int32{
	0, // 0: proto.TextToSpeechConverterService.Convert:input_type -> proto.ConvertTextToSpeechRequest
	1, // 1: proto.TextToSpeechConverterService.Convert:output_type -> proto.ConvertTextToSpeechResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_text_to_speech_proto_init() }
func file_text_to_speech_proto_init() {
	if File_text_to_speech_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_text_to_speech_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_text_to_speech_proto_goTypes,
		DependencyIndexes: file_text_to_speech_proto_depIdxs,
		MessageInfos:      file_text_to_speech_proto_msgTypes,
	}.Build()
	File_text_to_speech_proto = out.File
	file_text_to_speech_proto_rawDesc = nil
	file_text_to_speech_proto_goTypes = nil
	file_text_to_speech_proto_depIdxs = nil
}
