// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: video-to-audio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoToAudioConverterService_Convert_FullMethodName = "/proto.VideoToAudioConverterService/Convert"
)

// VideoToAudioConverterServiceClient is the client API for VideoToAudioConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoToAudioConverterServiceClient interface {
	Convert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse], error)
}

type videoToAudioConverterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoToAudioConverterServiceClient(cc grpc.ClientConnInterface) VideoToAudioConverterServiceClient {
	return &videoToAudioConverterServiceClient{cc}
}

func (c *videoToAudioConverterServiceClient) Convert(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VideoToAudioConverterService_ServiceDesc.Streams[0], VideoToAudioConverterService_Convert_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoToAudioConverterService_ConvertClient = grpc.ClientStreamingClient[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]

// VideoToAudioConverterServiceServer is the server API for VideoToAudioConverterService service.
// All implementations must embed UnimplementedVideoToAudioConverterServiceServer
// for forward compatibility.
type VideoToAudioConverterServiceServer interface {
	Convert(grpc.ClientStreamingServer[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]) error
	mustEmbedUnimplementedVideoToAudioConverterServiceServer()
}

// UnimplementedVideoToAudioConverterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoToAudioConverterServiceServer struct{}

func (UnimplementedVideoToAudioConverterServiceServer) Convert(grpc.ClientStreamingServer[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedVideoToAudioConverterServiceServer) mustEmbedUnimplementedVideoToAudioConverterServiceServer() {
}
func (UnimplementedVideoToAudioConverterServiceServer) testEmbeddedByValue() {}

// UnsafeVideoToAudioConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoToAudioConverterServiceServer will
// result in compilation errors.
type UnsafeVideoToAudioConverterServiceServer interface {
	mustEmbedUnimplementedVideoToAudioConverterServiceServer()
}

func RegisterVideoToAudioConverterServiceServer(s grpc.ServiceRegistrar, srv VideoToAudioConverterServiceServer) {
	// If the following call pancis, it indicates UnimplementedVideoToAudioConverterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoToAudioConverterService_ServiceDesc, srv)
}

func _VideoToAudioConverterService_Convert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoToAudioConverterServiceServer).Convert(&grpc.GenericServerStream[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VideoToAudioConverterService_ConvertServer = grpc.ClientStreamingServer[ConvertVideoToAudioRequest, ConvertVideoToAudioResponse]

// VideoToAudioConverterService_ServiceDesc is the grpc.ServiceDesc for VideoToAudioConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoToAudioConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VideoToAudioConverterService",
	HandlerType: (*VideoToAudioConverterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Convert",
			Handler:       _VideoToAudioConverterService_Convert_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "video-to-audio.proto",
}
