name: 'Build and Push Docker Image'
description: 'Build and push Docker image to Docker Hub'
inputs:
  service-name:
    description: 'Name of the service'
    required: true
  dockerfile-path:
    description: 'Path to the Dockerfile'
    required: true
  context:
    description: 'Build context'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-password:
    description: 'Docker Hub password'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ inputs.dockerhub-password }}

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

  - name: Build and Push Docker Image
    uses: docker/build-push-action@v4
    with:
      push: true
      tags: gkemhcs/${{ inputs.service-name }}--microservice-golang:${{ inputs.tag }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
      context: ${{ inputs.context }}
      file: ${{ inputs.dockerfile-path }}

