name: Build and Push Docker Images
on:
  push:
    paths:
      - 'src/frontend/**'
jobs:  
  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Build and Push Frontend Image
        uses: ./.github/actions/build-and-push
        with:
          service-name: 'frontend'
          dockerfile-path: 'src/frontend/Dockerfile'
          context: 'src/frontend'
          tag: 'latest'

  