name: Build and Push  Video to Audio Image

on:
  push:
    paths:
      - 'src/video-to-audio/**'

jobs:
  build-and-push-video-to-audio:
   
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@v4
      - name: Build and Push Video to Audio Image
        uses: ./.github/actions/build-and-push
        with:
          service-name: 'video-to-audio'
          dockerfile-path: 'src/video-to-audio/Dockerfile'
          context: 'src/video-to-audio'
          tag: "${{github.sha}}"
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

 